### ISSUE TITLE
Sign in with Facebook

### ISSUE THREAD

**Issue by bsab** [bsab/django-unifi-portal#1]

**Comment by JamesLodge** [comment]
I'm looking to use this for a client. I have everything setup and working. 

I'm using Nginx to proxy the app. 

One thing I'm struggling with are the Facebook API Oauth settings on the Facebook side. 

With everything i believe to be correct, when i click the "Sign in with Facebook" i receive 

Warning
You are not logged in: You are not logged in. Please log in and try again. 

I assume I'm missing something, as Facebook is not prompting for credentials.

**Comment by bsab** [comment]
Have you configured a Facebook application for your app?

**Comment by JamesLodge** [comment]
Yes and I've added the key and secret. 

I think my App config in Facebook might not be correct. 

I never get prompted for a username and password when clicking "SIGN IN WITH FACEBOOK"

**Comment by bsab** [comment]
Try to open the domain "facebok.com" for a while, just for the signing operation. Unfortunately this is a typical problem that Unify team is working on.

**Comment by JamesLodge** [comment]
I assumed Facebook never talks to the the Unifi controller, but just to Django Unifi Portal? 

I thought all the authentication happens on the Django side, then once authenticated, Django issues an API call to the unifi controller with the Mac address to allow access to the Internet.  

Do you have Facebook authentication working?

**Comment by bsab** [comment]
Yes, Facebook never talks to the controller but just to Django but the first authentication step( facebook login) happens on Facebook Side (for privacy reasons) then Facebook return a token to Django.

**Comment by JamesLodge** [comment]
Ok I have it working now. I had the wrong  OAuth redirect URIs in the Facebook App settings

Correct URI is: <FQDN>/auth/complete/facebook

**Comment by jMartich** [comment]
@JamesLodge you said you proxied the software? I got it running on apache with a virtual host at the moment, I have 2 things that are puzzling me. It's not loading the css "static" directory also when the device connects to the access point it sends it to <url>/guest/s/default where default is a unique number per AP. Here's the url 404 I'm getting

"<url>/Wifi-Portal/login?next=/guest/s/default/" so my question is how do I make it point to just /guest/s/default without the Wifi-Portal/login? To add a little color to the picture I have a symlink pointing back to where apache loads the django portal. Here's a tree view of the directory structure. 

.
├── guest
│   └── s
│       ├── OtherUnif-ID
│       │   ├── auth.php
│       │   ├── config.php.inc
│       │   ├── hotspot.sql
│       │   ├── index.php
│       │   └── main.css
│       ├── images
│       │   ├── body.png
│       │   ├── container-bottom.png
│       │   ├── container-top.png
│       │   └── elegant-shape.png
│       ├── OLD.UniFi-ID
│       │   ├── base_form.html
│       │   ├── base.html
│       │   ├── index.html
│       │   ├── logged_out.html
│       │   ├── login.html
│       │   └── registration.html
│       └── UniFi-ID -> /var/www/html/WiFiPortals/<Dir>/QA/jMtest/
└── QA
    └── jMtest
        ├── jMtest
        │   ├── __init__.py
        │   ├── __init__.pyc
        │   ├── settings.py
        │   ├── settings.pyc
        │   ├── unifi_settings.py
        │   ├── unifi_settings.pyc
        │   ├── urls.py
        │   ├── urls.pyc
        │   ├── wsgi.py
        │   └── wsgi.pyc
        ├── manage.py
        └── Wifi_Portal
            ├── admin.py
            ├── admin.pyc
            ├── apps.py
            ├── context_processor.py
            ├── context_processor.pyc
            ├── form_mixin.py
            ├── form_mixin.pyc
            ├── forms.py
            ├── forms.pyc
            ├── __init__.py
            ├── __init__.pyc
            ├── migrations
            │   ├── 0001_initial.py
            │   ├── 0001_initial.pyc
            │   ├── __init__.py
            │   └── __init__.pyc
            ├── models.py
            ├── models.pyc
            ├── pipeline.py
            ├── static
            │   ├── css
            │   │   ├── font-awesome.css
            │   │   └── font-awesome.min.css
            │   ├── fonts
            │   │   ├── FontAwesome.otf
            │   │   ├── fontawesome-webfont.eot
            │   │   ├── fontawesome-webfont.svg
            │   │   ├── fontawesome-webfont.ttf
            │   │   ├── fontawesome-webfont.woff
            │   │   └── fontawesome-webfont.woff2
            │   ├── img
            │   │   └── DjangoUniFi.png
            │   └── js
            │       └── jquery-2.1.1.min.js
            ├── templates
            │   ├── base_form.html
            │   ├── base.html
            │   ├── index.html
            │   ├── logged_out.html
            │   ├── login.html
            │   └── registration.html
            ├── tests.py
            ├── unifi_client.py
            ├── unifi_client.pyc
            ├── urls.py
            ├── urls.pyc
            ├── views.py
            └── views.pyc

As you can tell I have tried several things. I also want to apologize for my messy development server & not posting this under the correct issue, so please delete it if it makes everyone feel better & we can continue it in a new post.

**Comment by bsab** [comment]
Hello @JamesLodge, did you open the domain "facebook.com" (o relative IPs) to make it work ?

**Comment by JamesLodge** [comment]
@bsab on the unifi side I add facebook subnets on the Pre-Authorization Access
