### ISSUE TITLE
No module named "unifi_settings"

### ISSUE THREAD

**Issue by triomen** [bsab/django-unifi-portal#17]
Hi,

When I tried, on ubuntu : 
`$ pip install django-unifi-portal`
`$ pip install git+https://github.com/bsab/django-unifi-portal.git`
`cd django-unifi-portal/demo`
` $ python3 manage.py migrate django_unifi_portal`

It prints 
`ModuleNotFoundError : No module named unifi_settings`

Any idea ?

**Comment by ghost** [comment]
have you tried importing the attached unifi_settings.py from the READMEmd? or check in the project folder?
