### ISSUE TITLE
Quick Start guide errors

### ISSUE THREAD

**Issue by KevSex** [bsab/django-unifi-portal#2]
Hey,

I'm trying to install this using you Quick Start guide but seem to be having some issues in the setup.

I'm running in a virtual environment and I'm able to run the `pip install django_unifi_portal` command successfully however I'm having some issues with the `migrate` command.. 

I am met with the following:

    (env) root@ubuntu:~/unifi# pip install django-unifi-portal
    Collecting django-unifi-portal
      Using cached django-unifi-portal-0.0.2.zip
    Requirement already satisfied: django>=1.10 in ./env/lib/python2.7/site-packages (from django-unifi-portal)
    ... (output suppressed)
    Successfully installed Pillow-4.2.1 PyJWT-1.5.3 certifi-2017.7.27.1 chardet-3.0.4 django-braces-1.11.0 django-material-1.0.0 django-oauth-toolkit-1.0.0 django-rest-framework-social-oauth2-1.0.8 django-unifi-portal-0.0.2 djangorestframework-3.6.4 idna-2.6 oauthlib-2.0.4 olefile-0.44 python-openid-2.2.5 requests-2.18.4 requests-oauthlib-0.8.0 requests-toolbelt-0.8.0 six-1.11.0 social-auth-app-django-1.2.0 social-auth-core-1.4.0 urllib3-1.22
    (env) root@ubuntu:~/unifi# 
    (env) root@ubuntu:~/unifi# migrate django_unifi_portal
    Usage: migrate COMMAND ...`

    Available commands:
        compare_model_to_db          - compare MetaData against the current database state
        create                       - create an empty repository at the specified path
        create_model                 - dump the current database as a Python model to stdout
        db_version                   - show the current version of the repository under version control
        downgrade                    - downgrade a database to an earlier version
        drop_version_control         - removes version control from a database
        help                         - displays help on a given command
        make_update_script_for_model - create a script changing the old MetaData to the new (current) MetaData
        manage                       - creates a Python script that runs Migrate with a set of default values
        script                       - create an empty change Python script
        script_sql                   - create empty change SQL scripts for given database
        source                       - display the Python code for a particular version in this repository
        test                         - performs the upgrade and downgrade command on the given database
        update_db_from_model         - modify the database to match the structure of the current MetaData
        upgrade                      - upgrade a database to a later version
        version                      - display the latest version available in a repository
        version_control              - mark a database as under this repository's version control

    Enter "migrate help COMMAND" for information on a particular command.

    migrate: error: Invalid command django_unifi_portal

Django version:

    (env) root@ubuntu:~/unifi# python -c "import django; print(django.get_version())"
    1.11.5

Am I missing something?

**Comment by bsab** [comment]
Hello,
try to run the migration command after you have configured all the django app.

Take a look at the demo for mode details.

Let me know!
