### ISSUE TITLE
Won't pop up on IOS Android or OSX

### ISSUE THREAD

**Issue by fmiceli24** [bsab/django-unifi-portal#3]
The captive portal does not pop-up to the user.

User has to open browser and try to navigate in order to the portal to show up (in browser).

May be related to this: https://community.ubnt.com/t5/UniFi-Wireless/Captive-Portal-Apple-devices-not-automatically-showing-popup/td-p/1918579

Willing to test anything!!!

**Comment by JamesLodge** [comment]
I would suggest proxying the connect to the django app using Nginx (or Apache). I personally use Nginx. 

In your config you can add the following

 location / {
   
        if ($http_user_agent ~* (CaptiveNetworkSupport) ) {
        return 302 http://<#FQDN#>; }

            proxy_pass http://<IP ADDRESS>:<PORT>;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_Add_x_forwarded_for;
        }

MacOS and iOS Captive Network Assistant should then work.

**Comment by bsab** [comment]
Hello James,
what configuration file did you refer?

**Comment by JamesLodge** [comment]
Hi Sab, 

Sorry, I was just suggesting to fmiceli24 that as a way to get MacOS and iOS Captive Network Assistance to work was to proxy via Nginx and add the above to his Nginx config. My issue is with Facebook login.

**Comment by bsab** [comment]
No problem, it seems a good question you solved, so please, give us more details about it ;)

**Comment by JamesLodge** [comment]
Sure.  Here is the full Nginx config with SSL with comments. 

I''m actually running Django Unifi Portal on FreeBSD in a jail. Nginx is also running in the same jail, but this is just for testing. Production Nginx will be in a separate jail. 

### NGINX CONFIG ###

#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

   server {
                listen 80;
                server_name <#HOSTNAME#>;
                rewrite     ^   https://$server_name$request_uri? permanent;

                location /.well-known/acme-challenge/ {
                        root /usr/local/www/nginx/;
                        index index.html index.htm;
                        }

                }

   server {
        listen       443 ssl;
        server_name  <#HOSTNAME#>;

        # Lets Encrypt Certificate being used
        ssl_certificate      /usr/local/etc/letsencrypt/live/<FQDN>/fullchain.pem;
        ssl_certificate_key  /usr/local/etc/letsencrypt/live/<FQDN>/privkey.pem;

         location / {

        # Take the User Agent and returns a 302 redirect to the captive portal URL
        if ($http_user_agent ~* (CaptiveNetworkSupport) ) {
        return 302 http://<DJANGO UNIFI PORTAL FQDN>; }

            # This section proxies the connect to the Nginx on 443 to the Django app. Change the <IP 
            # ADDRESS> and <PORT> to your Django app
            proxy_pass http://<IP ADDRESS>:<PORT>;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_Add_x_forwarded_for;
        }
}
}

**Comment by fmiceli24** [comment]
Thanks.

Ended up solving it the same way.

Best,

2018-01-25 13:33 GMT-03:00 JamesLodge <notifications@github.com>:
