### ISSUE TITLE
Canceling Facebook Login Handling

### ISSUE THREAD

**Issue by JamesLodge** [bsab/django-unifi-portal#5]
Need to handle when a user cancels the Facebook login. 

Right now, and exception is thrown

Request Method: | GET
-- | --
http://<FQDN>/auth/complete/facebook/?error=access_denied&error_code=200&error_description=Permissions%20error&error_reason=user_denied&state=1mFmJIddk8Tmgpq8ZBgR2revYO32Shzr
1.11.7
AuthCanceled
Authentication process canceled: Permissions error
/usr/local/apps/virtenv/unifi_portal/lib/python2.7/site-packages/social_core/backends/oauth.py in process_error, line 378
/usr/local/apps/virtenv/unifi_portal/bin/python
2.7.14
['/usr/local/apps/virtenv/unifi',  '/usr/local/apps/virtenv/unifi_portal/lib/python27.zip',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7/plat-freebsd11',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7/lib-tk',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7/lib-old',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7',  '/usr/local/lib/python2.7/plat-freebsd11',  '/usr/local/lib/python2.7/lib-tk',  '/usr/local/apps/virtenv/unifi_portal/lib/python2.7/site-packages']
Thu, 25 Jan 2018 16:44:24 +0000

**Comment by JamesLodge** [comment]
Hi Seb, 

I have resolved this. 

I added the following

Settings.py 

MIDDLEWARE = [
....
'social_django.middleware.SocialAuthExceptionMiddleware',
}

AND

SOCIAL_AUTH_LOGIN_ERROR_URL = '/guest/s/default/'


Now more particularly AuthCanceled is handled and redirects the user back to login.

**Comment by bsab** [comment]
Hello James,
why don't you try to make a pull request to submit your solution? ;)

**Comment by JamesLodge** [comment]
Hi Sab, 

Pull request created. Hopefully its right, no git expert.

**Comment by JamesLodge** [comment]
This is now working correctly. 

For the handling of Facebook login exceptions debug must be disabled (DEBUG = False) otherwise you'll receive a debug report in the browser.
