### ISSUE TITLE
Session State - Cookie Expiry

### ISSUE THREAD

**Issue by JamesLodge** [bsab/django-unifi-portal#8]
Setting UNIFI_TIMEOUT_MINUTES doesn't seem to have an effect on the session cookie expiry. 

For example, I set UNIFI_TIMEOUT_MINUTES = 60 the unifi controller expiry is correct, yet the session cookie expiry is 14 days in the future.

**Comment by bsab** [comment]
Hello James,
i try to verify it ;)

**Comment by JamesLodge** [comment]
Actually I retract this issue, everything is work as expected.
